#LOGGING
logging:
    config: classpath:config/logback.xml
axis:
    dynamic-datasource: #动态数据源配置
          name: core
          url: jdbc:h2:file:./data/h2db;DB_CLOSE_ON_EXIT=FALSE
          username: sa
          password:
          maxPoolSize: 200
          properties: #druid 数据源配置
              filters: stat
              maxActive: 200
              initialSize: 5
              minIdle: 5
              maxWait: 5000
              timeBetweenEvictionRunsMillis: 60000
              minEvictableIdleTimeMillis: 300000
              validationQuery: select 'x' from dual
              testWhileIdle: true
              testOnBorrow: false
              testOnReturn: false
              poolPreparedStatements: true
              maxOpenPreparedStatements: 20
          icatch:
            max-actives: 100
            output-dir: ./data/atomikos
            log_base_dir: ./data/atomikos
            default-jta-timeout: 300000
    access-logger: on #开启访问日志